language: cpp

env:
  global:
   - secure: "Ll4Oa/ZV+CICeObtlR4I9bMEo3U+i9ilsGvgVfsTqrXcbyw/0v0e2ZPV+3g+Y/oqZJFWCnmccNcOia5oIqDL87lyH0w02VTb0B8bQxuTrkXHVXIVLREiVeTyAQOX9hXtrlsBQRB6JxTKPO2CmBpQH3SLLr5QciS0JIGp6OeVHPI="

compiler:
  - gcc
  - clang

matrix:
  allow_failures:
    - compiler: clang

addons:
  coverity_scan:
    project:
      name: "gree/flare"
      description: "my own flare repo"
    notification_email: kikehara@gmail.com
    build_command_prepend: "./configure"
    build_command: "make -j4"
    branch_pattern: coverity_scan

before_install:
  - sudo apt-get update
  - sudo apt-get install libtokyocabinet-dev
  - sudo apt-get install libboost-program-options-dev libboost-regex-dev libboost-serialization-dev libboost-thread-dev
  - sudo apt-get install uuid-dev libzookeeper-mt-dev
  - sudo apt-get install cutter-testing-framework valgrind

before_script:
  - travis_retry ./autogen.sh
  - travis_retry ./configure

script: make -j2 && make test && make check

