language: cpp

env:
  global:
   - secure: "CzgKaVZjkx1nyFnE8pcbjSTLygutqPt6mwEhHmlE3b2GQEcRXFaHOzyrcfbnJvBZ1awvtvHhVfV/tZwvkLDxOw/+Zj04QAna39C8utgC8hXXBvfocuAvpuIFWsub72CR8c+qBUe+5+nT6eNOWRwCU0DqXMLApNtgbReo8xo/ePU="

compiler:
  - gcc
  - clang

matrix:
  allow_failures:
    - compiler: clang

addons:
  coverity_scan:
    project:
      name: "ikehara/flare"
      description: "my own flare repo"
    notification_email: kikehara@gmail.com
    build_command_prepend: "./configure"
    build_command: "make -j4"
    branch_pattern: coverity_scan

before_install:
  - sudo apt-get update
  - sudo apt-get install libtokyocabinet-dev
  - sudo apt-get install libboost-program-options-dev libboost-regex-dev libboost-serialization-dev libboost-thread-dev
  - sudo apt-get install uuid-dev libzookeeper-mt-dev
  - sudo apt-get install cutter-testing-framework valgrind

before_script:
  - travis_retry ./autogen.sh
  - travis_retry ./configure

script: make -j2 && make test && make check

