name: nix-macos

on: [push, pull_request]

jobs:
  build-cache:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
          install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
          extra_nix_config: |
            experimental-features = nix-command flakes
          nix_path: nixpkgs=channel:nixos-unstable
      - run: |
          #ToDo: libredirect does not work, and we can not run flare-tests(.#test-flare) on nix-build.
          #nix build .#test-flare -L
          nix build .#flare -L
