{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "flare-operator.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "flare-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "flare-operator.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
{{- end }}
